#! /bin/bash

rm timings_06*.dat
rm timings_12*.dat
rm timings_20*.dat
rm shell_area_06*.dat
rm shell_area_12*.dat
rm shell_area_20*.dat
rm hollow_sphere_volume_06*.dat
rm hollow_sphere_volume_12*.dat
rm hollow_sphere_volume_20*.dat
rm nvertices_06*.dat
rm nvertices_12*.dat
rm nvertices_20*.dat
rm gravity_06*.dat
rm gravity_12*.dat
rm gravity_20*.dat
rm shell_edge_06*.dat
rm shell_edge_12*.dat
rm shell_edge_20*.dat

for l in 2 4 8 12 16 24 32 48 64 96 128 160 192 224 256; do

   echo '----------------------------------'
   ./spider -level $l -mtype 06 -nlayer $l -equiangular 0
   cat fort.999 >> timings_06a.dat
   cat fort.888 >> shell_area_06a.dat
   cat fort.777 >> hollow_sphere_volume_06a.dat
   cat fort.555 >> nvertices_06a.dat
   cat fort.444 >> gravity_06a.dat
   cat fort.889 >> shell_edge_06a.dat
   echo '----------------------------------'
   ./spider -level $l -mtype 06 -nlayer $l -equiangular 1
   cat fort.999 >> timings_06b.dat
   cat fort.888 >> shell_area_06b.dat
   cat fort.777 >> hollow_sphere_volume_06b.dat
   cat fort.555 >> nvertices_06b.dat
   cat fort.444 >> gravity_06b.dat
   cat fort.889 >> shell_edge_06b.dat

   echo '----------------------------------'
   ./spider -level $l -mtype 12 -nlayer $l -equiangular 0
   cat fort.999 >> timings_12a.dat
   cat fort.888 >> shell_area_12a.dat
   cat fort.777 >> hollow_sphere_volume_12a.dat
   cat fort.555 >> nvertices_12a.dat
   cat fort.444 >> gravity_12a.dat
   cat fort.889 >> shell_edge_12a.dat
   echo '----------------------------------'
   ./spider -level $l -mtype 12 -nlayer $l -equiangular 1
   cat fort.999 >> timings_12b.dat
   cat fort.888 >> shell_area_12b.dat
   cat fort.777 >> hollow_sphere_volume_12b.dat
   cat fort.444 >> gravity_12b.dat
   cat fort.889 >> shell_edge_12b.dat

   echo '----------------------------------'
   ./spider -level $l -mtype 20 -nlayer $l
   cat fort.999 >> timings_20.dat
   cat fort.888 >> shell_area_20.dat
   cat fort.777 >> hollow_sphere_volume_20.dat
   cat fort.555 >> nvertices_20.dat
   cat fort.444 >> gravity_20.dat
   cat fort.889 >> shell_edge_20.dat

done
